api_root_path: ''
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
cors_exposed_headers: null
db_name: uos
docs_url: /docs
enable_opentelemetry: false
generate_correlation_id: true
host: 127.0.0.1
kafka_compression_type: null
kafka_dlq_topic: dlq
kafka_enable_dlq: false
kafka_max_message_size: 1048576
kafka_max_retries: 0
kafka_retry_backoff: 0
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
log_traceback: true
mongo_dsn: '**********'
mongo_timeout: 300
openapi_url: /openapi.json
otel_trace_sampling_rate: 1.0
port: 8080
service_instance_id: '1'
service_name: uos
workers: 1
