[project]
# please adapt to package name
name = "my_microservice"
version = "0.1.0"
description = "My-Microservice - a short description"
dependencies = [
    "typer >= 0.15",
    "ghga-service-commons[api] >= 4.0",
    "ghga-event-schemas >= 6.0",
    "hexkit[akafka,s3,mongodb] >= 4.5",
]

[project.urls]
# please adapt to package name
Repository = "https://github.com/ghga-de/my-microservice"

[project.scripts]
# please adapt to package name
my-microservice = "my_microservice.__main__:run"
