[project]
name = "uos"
version = "2.0.0"
description = "Upload Orchestration Service - A service providing a web-accessible management and auth layer over upload-path file services."
dependencies = [
    "typer >= 0.15",
    "ghga-service-commons[api,auth,crypt] >= 4.2",
    "ghga-event-schemas ~= 10.1",
    "hexkit[akafka,mongodb,opentelemetry] >= 8.1",
]

[project.urls]
Repository = "https://github.com/ghga-de/upload-orchestration-service"

[project.scripts]
uos = "uos.__main__:cli"
